In [28]:
import torch
import torch.nn as nn

In [29]:
torch.Tensor(2, 3)

tensor([[0.0000e+00, 0.0000e+00, 3.3497e-09],
        [2.1027e+20, 3.3856e-06, 1.6987e-07]])

In [30]:
nn.Parameter(torch.Tensor(2,3))

Parameter containing:
tensor([[6.7262e-44, 7.9874e-44, 1.1771e-43],
        [6.7262e-44, 7.1466e-44, 8.1275e-44]], requires_grad=True)

In [31]:
b = torch.randn(2,3)
b

tensor([[ 0.7628, -1.6425, -1.4857],
        [ 0.4624,  0.4417, -1.0390]])

In [32]:
b.uniform_(0, 1)

tensor([[0.4614, 0.1125, 0.6703],
        [0.1231, 0.2875, 0.3648]])

In [33]:
c = torch.zeros(2,3)
c

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [34]:
c.size()

torch.Size([2, 3])

In [35]:
c = c.unsqueeze(0)
c

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [36]:
c.size()

torch.Size([1, 2, 3])

In [48]:
t1 = torch.randn(3,4)
t2= torch.randn(3,4)
l1 = []
print(t1)
print(t2)
print(l1)

tensor([[ 1.0085,  1.3747, -1.2875,  0.8424],
        [-0.2851, -1.5225, -1.1119, -1.5243],
        [-0.4864,  0.8463, -0.5516,  0.2596]])
tensor([[-0.8208, -1.9864, -1.3729, -0.5153],
        [-0.7217,  0.5975,  1.1512,  1.1755],
        [ 0.6672, -1.9025, -0.6683, -0.4970]])
[]


In [49]:
l1.append(t1.unsqueeze(0))
l1.append(t2.unsqueeze(0))
l1

[tensor([[[ 1.0085,  1.3747, -1.2875,  0.8424],
          [-0.2851, -1.5225, -1.1119, -1.5243],
          [-0.4864,  0.8463, -0.5516,  0.2596]]]),
 tensor([[[-0.8208, -1.9864, -1.3729, -0.5153],
          [-0.7217,  0.5975,  1.1512,  1.1755],
          [ 0.6672, -1.9025, -0.6683, -0.4970]]])]

In [50]:
l1 = torch.cat(l1,dim=0)
l1

tensor([[[ 1.0085,  1.3747, -1.2875,  0.8424],
         [-0.2851, -1.5225, -1.1119, -1.5243],
         [-0.4864,  0.8463, -0.5516,  0.2596]],

        [[-0.8208, -1.9864, -1.3729, -0.5153],
         [-0.7217,  0.5975,  1.1512,  1.1755],
         [ 0.6672, -1.9025, -0.6683, -0.4970]]])

In [51]:
l1.size()

torch.Size([2, 3, 4])

In [52]:
l1.transpose(0,1)

tensor([[[ 1.0085,  1.3747, -1.2875,  0.8424],
         [-0.8208, -1.9864, -1.3729, -0.5153]],

        [[-0.2851, -1.5225, -1.1119, -1.5243],
         [-0.7217,  0.5975,  1.1512,  1.1755]],

        [[-0.4864,  0.8463, -0.5516,  0.2596],
         [ 0.6672, -1.9025, -0.6683, -0.4970]]])

In [64]:
a = torch.randn(2,3)
a

tensor([[-1.4251, -0.5673, -0.3780],
        [ 0.4909, -0.6237, -1.4178]])

In [65]:
a.transpose(0,1)

tensor([[-1.4251,  0.4909],
        [-0.5673, -0.6237],
        [-0.3780, -1.4178]])